name: "Due Date Changed"
description: "Notify when project's due date field changed"
author: "Emily Lambrou"
branding:
  icon: 'notification'
  color: 'green'
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  gh_token:
    description: "GitHub Personal Access Token"
    required: true
  project_number:
    description: "The Project Number"
    required: true 
  duedate_field_name:
    description: "The field name for the due date"
    required: true
    default: 'Due Date'
  notification_type:
    description: "The type of notification (comment,email)"
    required: true
    default: 'comment'
  enterprise_github:
    description: "Determines if the GitHub is the enterprise ot not (True,False)"
    required: false
    default: 'False'
  repository_owner_type:
    description: "The type of the repository owner (organization, user)"
    required: true
    default: 'user'
  dry_run:
    description: "DryRun Mode (True, False)"
    required: false
    default: 'False'
